### ISSUE TITLE
FirstStep

### ISSUE THREAD

**Issue by Flekysek** [NataliaTencerova/PDF_to_Excel#5]
**Description:**
Create first project that will do something really small and we will be able to build it.

**TODO:**
1. [x] Create YOUR branch in this ticket
2. [x] Write into the console something nice
3. [x] Create all of the files for building of project 
4. [x] Exclude the build from git
5. [x] push it and make PR
6. [ ] merge it in to the master

**Comment by NataliaTencerova** [comment]
Build the main file using this command "pyinstaller --onefile main.py"
